[[criteria]]
== Composability Criteria

=== Introduction (non-normative)

The CX Composability Criteria comprise a set of rules that determine which
RISC-V custom extensions are deemed _composable_, forming a subcategory
of custom extensions known as _composable custom extensions_.

The Criteria promote dependable reusability of CXs in diverse composition
settings by ensuring that composable custom extensions exhibit composition
invariance and portability, so _that which works separately, works
together_.

A custom extension is dependably composable when it satisfies:

1. _Composition invariance_: the extension's functional behavior is
unchanged in the presence or absence of other CXs;

2. _Portability_: the functional behavior of a system of harts and CXs,
including this CX, is the same regardless of what hardware implements
them.

=== Requirements (non-normative)

1. Support composition invariance so that the functional behavior of a
CX does not change in the presence/absence of other CXs;

2. Support portability so that the functional behavior of a CX does not
change across different hardware implementations of the hart or the CX;

3. Support stateful CXs;

4. Support CXs that access integer registers.

==== Potential requirements

1. Support CXs that access floating-point registers, vector registers,
and shared memory.

=== Criteria

A custom instruction is a RISC-V instruction with a major opcode of `custom-0`/`-1`/`-2`/`-3`.

A custom extension comprises a set of custom instructions plus a set
of RISC-V custom CSRs plus extension state, with a specified functional
behavior and state model.

A custom extension is a _composable_ custom extension _if-and-only-if_:

1. Its instructions appear to execute in program order on the local hart.

2. Each of its instructions only reads some _composable state_, computes
a pure function of this state (and no other state), then either raises
an exception, or writes some composable state. _Composable state_
comprises the selected extension's state, including its custom CSRs,
plus the hart's integer registers, floating-point registers, `fcsr` CSR,
vector registers, vector context status in `mstatus` and in `vsstatus`,
`vtype`, `vl`, `vlenb`, `vstart`, `vcsr` CSRs, and loads and stores to
memory as if performed by the local hart.

3. Instructions that access memory appear to execute in program order
on the local hart. These instructions follow RVWMO at the instruction
level. If the Ztso extension is implemented, these instructions
additionally follow RVTSO at the instruction level.

4. Instructions that access memory may raise the usual memory access
exceptions.

5. The extension is specified such that its functional behavior
is identical on any implementation that meets its requirements and
specification.

=== Discussion (non-normative)

To write-up:

* How to sift through multiverse of possible custom extensions to those that are dependable to compose
* Approach: "what's allowed from 0" criteria --vs.-- "what's not allowed from infinity" criteria
* Instruction-at-a-time model -- disallow surprising "continuous" sharing of hart state
* Custom instruction accesses to memory: slavishly recapitulates -V vector memory consistency model
* Isolation enables composition: no access to other extensions' state, no access to other state contexts of this extension
* Accomodates both unresolved 1:1 hart:extension state model vs. m:n extension state instances model
* Looks ahead to implementable composable hardware unit models / logic interface support
