[[external]]
[appendix]
= External Specifications

This section contains changes to external specifications for RISC-V
Composable Custom Extensions.  It is intended that as these sections
are incorporated into the upstream specification or similar, they will
be removed from this document.  External specifications include both
RISC-V and non-RISC-V specifications and other information
specification mechanisms.

=== Devicetree

This section includes devicetree bindings for composable custom
extensions that will be submit upstream to Linux.

[NOTE]
====
The devicetree bindings in the Linux repository are also used by
multiple projects other than Linux.
====

[TIP]
====
A future revison may add bindings for specifying microarchitectural
details, such as performance characteristics or the connectivity
between composable custom extensions and harts, so this information is
available to the kernel and it can act accordingly.
====

This file will be submit as
`Documentation/devicetree/bindings/riscv/cxs.yaml`.

[,yaml]
----
include::cxs.yaml[]
----

=== ACPI

[NOTE]
====
This section will be incorporated into the ACPI Specification.
====

[TIP]
====
Add definition for ACPI table for identifying composable custom
extension on harts and any necessary parameters, such as state size.

If necessary add support for identifying multiple CX instances and
heterogeneous per-hart accessibility of these CX instances.
====


=== User Space ABI

[NOTE]
====
This section will be incorporated into the RISC-V psABI Specification.
====

The following ELF flag will be added to `e_flags`:

* `EF_RISCV_RVCX`: This bit is set when the binary is compiled with
  the Composable Custom Extension aware calling convention.

The policy for linking for the CX field is as follows:

* Linker should report errors when linking object files with different
  values for the CX field.

[NOTE]
====
Evaluate if the ELF flag is necessary, for either or both calling
conventions.
====

==== Default Calling Convention

Custom extension state is not preserved across function calls.

`cxsel` is not preserved across function calls.

Procedures may assume that `cxsel` is zero upon entry.  Procedures may
assume that `cxsel` is zero upon return from a procedure call.

[NOTE]
====
Application software that sets `cxsel` to a non-zero value must set it
to zero before either returning or calling another procedure.
====

==== Composable Custom Extension Calling Convention

Procedures may indicate they are utilizing this calling convention
with the function attribute `riscv_cx_cc`.

Custom extension state is preserved across function calls.

`cxsel` is preserved across function calls.

Procedures may assume that `cxsel` is zero upon entry.

[NOTE]
====
Application software that sets `cxsel` to a non-zero value must set it
to zero before calling another procedure.
====

=== User Space API

[TIP]
====
Specify an API that provides a uniform CX programming model including
CX naming, discovery, versioning, CX selection, and error handling and
correct composition of CX libraries.

If necessary the API will support both the singleton CX model and the
multiple CX instance model.
====

=== SBI

[NOTE]
====
This section will be incorporated into the RISC-V SBI Specification.
====

[TIP]
====
It is unclear if an SBI extension is necessary.  It will be specified
as needed.
====

=== Linux

This section describes the user space interface for composable custom
extensions in Linux.

[NOTE]
====
This interface supports using a single shared context per thread.
====

==== hwprobe

The following keys are added for the `hwprobe()` syscall:

* `RISCV_HWPROBE_KEY_CXID_0`: A bitmask indicating which CX IDs are
  available to user space.  Bit 0 indicates CX ID 0, and so on.

* `RISCV_HWPROBE_KEY_CX1_CONTEXT_SIZE` +
  `RISCV_HWPROBE_KEY_CX2_CONTEXT_SIZE` +
  ⋮ +
  `RISCV_HWPROBE_KEY_CX63_CONTEXT_SIZE`: Indicates the size in bytes
  of one state context for the specified custom extension.

* `RISCV_HWPROBE_KEY_CX1_VENDORID` +
  `RISCV_HWPROBE_KEY_CX2_VENDORID` +
  ⋮ +
  `RISCV_HWPROBE_KEY_CX63_VENDORID`: Indicates the vendor ID for the
  specified custom extension.

* `RISCV_HWPROBE_KEY_CX1_ARCHID` +
  `RISCV_HWPROBE_KEY_CX2_ARCHID` +
  ⋮ +
  `RISCV_HWPROBE_KEY_CX63_ARCHID`: Indicates the architecture ID for
  the specified custom extension.

* `RISCV_HWPROBE_KEY_CX1_IMPID` +
  `RISCV_HWPROBE_KEY_CX2_IMPID` +
  ⋮ +
  `RISCV_HWPROBE_KEY_CX63_IMPID`: Indicates the implementation ID for
  the specified custom extension.

* `RISCV_HWPROBE_KEY_IMA_EXT_0`
** `RISCV_HWPROBE_EXT_CX`: The Composable Custom Extensions Extension
   is supported.  This represents the CX framework and not a specific
   custom extension.

==== Composable Custom Extensions Userspace Interface

This file will be submit as `Documentation/arch/riscv/cx.rst`.

[,rst]
----
include::cx.rst[]
----
