[[isa-unpriv]]
:secnums:
[[isa-cx-mux]]
== Unprivileged CX Multiplexing

The unprivileged Composable Custom Extensions Extension supports _CX
multiplexing_ of the custom instruction and custom CSR spaces, so that
multiple custom extensions (of arbitrary custom instructions and custom
CSRs) can coexist conflict-free within a system.

The extension supports a model in which software first _discovers_ and
_selects_ a hart's current CX prior to issuing its custom instructions
or accessing its custom CSRs (collectively _"CX instructions"_). These
CX instructions are then executed by the selected custom extension and
ignored by others.

NOTE: There is a proposal to support simultaneous selection of more
than one CX on a hart, for example, one for each of
`custom-0/1/2/3`. This may require multiple selections CSRs, `cxsel0`,
`cxsel1`, etc., and/or changes to `cxsetsel`.

=== CX Extension Programmer's Model

The CX Extension adds one unprivileged CSR (`cxsel`) and one unprivileged
instruction (`cxsetsel`) to a base RISC-V ISA.

NOTE: There is a proposal to exclusively use Zicsr instructions or new
instruction(s), but not a combination of both, to access `cxsel`.

.New CX CSRs
[cols="2,2,2,10"]
[%autowidth]
|===
| Address | Privilege | Name   | Description

| 0xTBD | URO | cxsel | CX selector
|===

=== CX Selector Register (`cxsel`)

The read-only XLEN-wide CX selector CSR, `cxsel` specifies the
extension used to execute CX instructions, and can only be updated by
the `cxsetsel` instruction.

`cxsel` is a WARL register that must be able to hold all legal
selector values.

Legal selector values are:

- -1, which is the only legal INVALID selector value
- 0, which indicates the BUILT-IN custom extension
- any value returned by the platform-specific discovery
mechanism for use as a selector.

NOTE: Any illegal value written to `cxsel` will be mapped to -1, the INVALID selector value.

NOTE: Software should assume selectors are XLEN bits wide, but the precise layout or meaning of individual bits can vary.

NOTE: A CX selector may be _hart specific_.

The value of `cxsel` is 0 at reset.

NOTE: This will select the built-in custom extension on reset to
provide compatibilty with software that does not support composable
custom extensions.

=== CX Set Selector Instruction (`cxsetsel`)

TBD (but non-custom) 32-bit instruction `cxsetsel rd,rs1` atomically
swaps the value in `cxsel` and an integer register.  It writes the
initial value of `x[rs1]` to `cxsel`, and if `rd` is not `x0` it
writes the initial value of `cxsel` to `x[rd]`.

=== CX Multiplexing

The CX selector value in `cxsel` determines which specific CX instance
granted to this hart, or the built-in custom extensions, executes
CX instructions.

When `cxsel` is 0, CX instructions are executed by the BUILT-IN custom
extension.

When `cxsel` is any other legal value, CX instructions are executed by
the selected extension.

When `cxsel` is INVALID, CX instructions are treated as illegal
instructions.
