[[isa-priv]]
== Privileged Opcode and State Multiplexing

=== Programmer's Model

The CX Extension adds the following privileged CSRs.

.New CX CSRs
[cols="2,2,2,10",options="header",align="center"]
[%autowidth]
|===
| Address | Privilege | Name   | Description
| 0xTBD | SRW | `scxstp`  | CX selection translation pointer.
| 0xTBD | SRW | `scxxs0`  | CX context status.
| 0xTBD | SRW | `scxxs1`  | CX context status, RV32 only.
| 0xTBD | SRW | `scxxs2`  | CX context status.
| 0xTBD | SRW | `scxxs3`  | CX context status, RV32 only.
|===

.New CX CSRs for `Zxxx`
[cols="2,2,2,10",options="header",align="center"]
[%autowidth]
|===
| Address | Privilege | Name   | Description
| 0xTBD | SRW | `scx1xs0`  | CX 1 context status
| 0xTBD | SRW | `scx1xs1`  | CX 1 context status, RV32 only.

| 0xTBD | SRW | `scx2xs0`  | CX 2 context status
| 0xTBD | SRW | `scx2xs1`  | CX 2 context status, RV32 only.

|       |     | ⋮       |

| 0xTBD | SRW | `scx63xs0` | CX 63 context status
| 0xTBD | SRW | `scx63xs1` | CX 63 context status, RV32 only.
|===

=== CX Selection Translation Pointer (`scxstp`)

The read-write XLEN-wide CX selection translation pointer, `scxstp`,
broadly controls the availability of composable custom extensions and
the interpretation of the unprivileged `cxsel` register.

The upper four bits of `scxstp` indicate one of the following modes:

.Selection Translation Modes
[cols="1,1",options="header",align="center"]
[%autowidth]
|===
| Value | Meaning
| 0 | Disabled
| 1 | Direct
| 2 | Indirect (`Zxxx` only)
| 3-15 | Reserved
|===

==== Disabled

When `scxstp.mode` is set to `Disabled`, the CX framework is disabled.  The
remaining bits of `scxstp` are reserved.

When the CX framework is disabled, all use of CX opcodes and CSRs will
trigger an illegal instruction exception.  The custom opcode space
will map to the built-in custom extension.

==== Direct

When `scxstp.mode` is set to `Direct`, the CX framework is enabled in
direct mode.  The remaining bits of `scxstp` are reserved.

In direct mode, `cxsel` is interpreted directly as a CX ID.  When
`Zxxx` is implemented, the context index is zero.

==== Indirect

When `scxstp.mode` is set to `Indirect`, the CX framework is enabled
in indirect mode.  The lower bits of `scxstp` provide a PPN for the CX
selection translation table, a memory mapped table of the format
described below.  The CX selection translation table is 4 kiB.

Each entry in the CX selection translation table is 32-bits.

- bit 31: valid
- bit 30-16: reserved
- bit 15-8: context index
- bit 7-0: CX ID

`cxsel` is interpreted as an index into the CX selection translation
table.  If the selected CX selection translation table entry has the
valid bit clear, attempts to execute custom opcodes will result in an
illegal instruction exception.

If the selected CX selection translation table entry specifies a
invalid context index or an invalid CX ID, attempts to execute custom
opcodes will result in an illegal instruction exception.

If all fields of the selected CX selection translation table entry are
valid, attempts to execute custom opcodes will be performed by the
indicated CX ID and context index.

=== CX Context Status

==== Extension Status

Four registers, `scxxs0` through `scxxs3`, hold the context state
status for each extension in RV32.  In RV64, the odd numbered
registers are invalid.

There are two bits of context state status for each composable custom
extension, the meaning of which is analogous to the FS and VS bits of
the `mstatus` register.  The location of bits is based on the CX ID of
the extension.

If the status bits corresponding to a given CX ID are set to
`Initial`, any attempt to execute custom opcodes mapped to that
extension will result in an illegal instruction exception.

When `scxstp.mode` is `Direct`, the bits in `scxxs__n__` for CX IDs greater
than zero are writable and reflect the status of and control context
zero of the respective extension.

When `scxstp.mode` is `Indirect`, the bits in `scxxs__n__` for CX IDs
greater than zero are read-only and reflect a summary of the maximal
status of all contexts for the respective extension.

==== Additional Extension Status

The additional extension status registers, `scx1xs0` and `sxc1xs1`
through `scx63xs0` and `scx63xs1`, are only present if `Zxxx` is
implemented and an extension with the corresponding CX ID is present.
For RV32, a pair of registers is used for each CX ID.  For RV64, only
the even register (`scx__n__xs0`) is present.

The additional extension status registers contain the status of the
state for each context within each composable custom extension.  Each
CX ID has a corresponding registers with bits for all contexts.  The
location of the bits within the register indicate the context index.
The meaning of bits is analogous to the `scxxs__n__` bits for each
extension when `Zxxx` is not present.

NOTE: The `scx__m__xs__n__` registers are expected to become indirect
CSRs.  Thus, `Zxxx` will require `Sscsrind`.

=== Smststeen

The CX framework adds a CX bit to `mstateen`, `sstateen`, and `hstateen`.

[NOTE]
====
Composable custom extensions does not require `Smststeen`.
====

[TIP]
====
`mstateen0.C`, `sstateen0.C`, and/or `hstateen0.C`, must be set to
enable access to custom state, including that within composable custom
extensions.
====
