[[isa-unpriv]]
:secnums:
== Unprivileged CX Multiplexing

The unprivileged Composable Custom Extensions Extension supports _CX
multiplexing_ of the custom instruction and custom CSR spaces, so that
multiple custom extensions (of arbitrary custom instructions and custom
CSRs) can coexist conflict-free within a system.

The extension supports a model in which software first _discovers_ and
_selects_ a hart's current CX prior to issuing its custom instructions
or accessing its custom CSRs (collectively _"CX instructions"_). These
CX instructions are then executed by the selected custom extension and
ignored by others.

NOTE: There is a proposal to support simultaneous selection of more
than one CX on a hart, for example, one for each of
`custom-0/1/2/3`. This may require multiple selections CSRs, `cxsel0`,
`cxsel1`, etc., and/or changes to `cxsetsel`.

=== CX Extension Programmer's Model

The CX Extension adds one unprivileged CSR (`cxsel`) and one unprivileged
instruction (`cxsetsel`) to a base RISC-V ISA.

.New CX CSRs
[cols="2,2,2,10"]
[%autowidth]
|===
| Address | Privilege | Name   | Description

| 0xTBD | URO | cxsel | CX selector
|===

=== CX Selector Register (`cxsel`)

`cxsel` is an XLEN-bit read-only register. It is a WARL register that
must be able to hold all valid selector values.  It need not be
capable of holding all possible invalid selector values.  Prior to
writing `cxsel`, implementations may convert an invalid value into
some other invalid value that `cxsel` is capable of holding.

NOTE: Invalid selector values may also be referred to as null selectors.

Valid selector values are 0, which indicates the built-in custom
extension, and any value returned by the platform specific discovery
mechanism for use as a selector.

A value of all 1s is an invalid selector value.

[NOTE]
====
The all 1s value may be used by software to aid in debugging
uninitialized variables.

It is not required that the all 1s value be a legal value.
====

NOTE: There is a proposal to define an additional selector value to
indicate 'no CX'.

NOTE: A CX selector may be _hart specific_.

The value of `cxsel` is 0 at reset.

NOTE: This will select the built-in custom extension on reset to
provide compatibilty with software that does not support composable
custom extensions.

=== CX Set Selector Instruction (`cxsetsel`)

TBD (but non-custom) 32-bit instruction `cxsetsel rd,rs1` atomically
swaps the value in `cxsel` and an integer register.  It writes the
initial value of `x[rs1]` to `cxsel`, and if `rd` is not `x0` it
writes the initial value of `cxsel` to `x[rd]`.

=== CX Multiplexing

The CX selector value in `cxsel` determines which specific CX instance
granted to this hart, or the built-in custom extensions, executes
CX instructions.

When `cxsel` is 0, CX instructions are executed by the built-in custom
extension.

When `cxsel` is any other valid value, CX instructions are executed by
the selected extension.

When `cxsel` is invalid, CX instructions are treated as illegal
instructions.

NOTE: There is a proposal to require that CX instructions trap when
`cxsel` is invalid.
